[package]
name = "doge_transport"
version = "0.2.4"
authors = ["Darrion Whitfield <dwhitfield@ramfield.net>"]
description = "The doge lib for preparing and communicating with dns servers and protocols"
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]

# dns wire protocol
doge_dns = "1.0.1" # Visibility errors below 1.0.1

# logging
log = "0.4"

# tls networking
native-tls = { version = "0.2", optional = true }

# http response parsing
httparse = { version = "1.3", optional = true }

rustls = { version = "0.19", optional = true }

webpki = { version = "0.22.4", optional = true }

webpki-roots = { version = "0.26.1", optional = true }

cfg-if = "1"

[features]
default = []  # these are enabled in the main dog crate

with_tls   = []
with_https = ["httparse"]

with_nativetls = ["native-tls"]
with_nativetls_vendored = ["native-tls", "native-tls/vendored"]
with_rustls = ["rustls", "webpki-roots", "webpki"]
